server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jsondemo
    username: postgres
    password: root
    
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create-drop
        
        
